# Generated by Django 3.2.8 on 2021-10-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Descripción'),
        ),
    ]
