# Generated by Django 3.2.8 on 2021-12-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(default=' ', max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
