# Generated by Django 3.2.8 on 2021-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20211223_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(default=' ', max_length=150, verbose_name='Apellido'),
        ),
    ]
