# Generated by Django 3.2.8 on 2022-01-03 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20220103_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnas',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='alumnas',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumnas',
            name='names',
            field=models.CharField(max_length=100, verbose_name='Nombre/s'),
        ),
        migrations.AlterField(
            model_name='alumnas',
            name='surnames',
            field=models.CharField(max_length=100, verbose_name='Apellido/s'),
        ),
    ]
