# Generated by Django 3.2.8 on 2022-01-03 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20220103_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnas',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Ingreso'),
        ),
    ]
