# Generated by Django 3.2.8 on 2022-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_alumnas_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnas',
            name='email',
            field=models.EmailField(default=1, max_length=70, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
