# Generated by Django 3.2.8 on 2022-01-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alumnas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnas',
            name='names',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='alumnas',
            name='surnames',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
    ]
