# Generated by Django 3.2.8 on 2022-01-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20220109_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnas',
            name='back_pain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Patología de Columna'),
        ),
        migrations.AddField(
            model_name='alumnas',
            name='diseases',
            field=models.CharField(choices=[('anemia', 'Anemia'), ('asthma', 'Asma'), ('back_pain', 'Dolor de Espalda'), ('cancer', 'Cáncer'), ('diabetes', 'Diabetes'), ('stroke', 'Accidente Cerebro Vascular'), ('epilepsy', 'Epilepsia'), ('depression', 'Depresión'), ('arthritis', 'Artritis'), ('none', 'Ninguna'), ('others', 'Otras')], default='anemia', max_length=35, verbose_name='Enfermedades'),
        ),
        migrations.AddField(
            model_name='alumnas',
            name='heart_disease',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Enfermedad Cardíaca'),
        ),
        migrations.AddField(
            model_name='alumnas',
            name='observations',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='alumnas',
            name='pain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dolor Óseo o Muscular'),
        ),
    ]
