# Generated by Django 3.2.8 on 2022-01-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20220110_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnas',
            name='goals_others',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Otras'),
        ),
    ]
