# Generated by Django 3.2.8 on 2022-01-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alumnas_goals_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnas',
            name='date_of_birth',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumnas',
            name='goals_others',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Otros'),
        ),
    ]
