# Generated by Django 3.2.8 on 2022-01-10 20:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_alumnas_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnas',
            name='goals',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('flexibility', 'Flexibilidad'), ('strength', 'Fuerza'), ('relax', 'Relajación'), ('posture', 'Postura disminución del estrés'), ('others', 'Otros')], max_length=41, verbose_name='Objetivos'),
        ),
    ]
